apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-api
  labels:
    app: money-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: money-api
  template:
    metadata:
      labels:
        app: money-api
    spec:
      containers:
      - name: money-api
        image: username/money_api:0.0.1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: money-api-service
spec:
  selector:
    app: money-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
